{{- if .Values.createNewServiceAccount }}
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pipelines-agent-manager
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups: ["", "batch", "extensions", "apps"]
  resources: ["*"]
  verbs: ["*"]
{{- end }}